#
# Container for OT.one frontend
#
# Notes:
# - The patch changes the name of the crossbar websocket connection in 
#   communication.js to otone.local to make testing easier so one could
#   set a name of the ot.one host in /etc/hosts
#

FROM common-build

COPY * /home/sandbox-frontend-master/
WORKDIR /home/sandbox-frontend-master
RUN pip3 install -r requirements.txt \
    && rm -rf /var/cache/apk/*

ENTRYPOINT ["tar", "-cvz", "/usr/lib/python3.5/site-packages/", "/home/sandbox-frontend-master"]
